name: "Python Container Action Template"
description: "Get started with Python Container actions"
author: "Jacob Tomlinson"
inputs:
  BotToken:
    description: "Bot Token"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
